version: '3'

services:
  app:
    container_name: heritage-app
    build: ./app
    volumes:
      - ../heritage:/var/www/html
    depends_on:
      - db

  nginx:
    image: nginx:1.17.6
    container_name: heritage-nginx
    ports:
      - 8000:80
    volumes:
      - ../heritage:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx/:/var/log/nginx/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

  db:
    image: mysql:5.7
    container_name: heritage-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: heritage-db
      MYSQL_PASSWORD: root
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3308:3306

  phpmyadmin:
    container_name: heritage_phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: heritage-db
      MYSQL_PASSWORD: root
    ports:
      - 8080:80