version: '3'

services:
  app:
    container_name: heritage-app
    build: ./app
    volumes:
      - ../metroad:/var/www/html
    depends_on:
      - db

  nginx:
    image: nginx:1.17.6
    container_name: heritage-nginx
    ports:
      - 8000:80
    volumes:
      - ../heritage:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx/:/var/log/nginx/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

  db:
    image: mysql:5.7
    container_name: heritage-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: heritage
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      TZ: 'Asia/Tokyo'
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./logs/mysql/:/var/log/mysql/
    ports:
      - 3308:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: heritage-phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=heritage
      - PMA_PASSWORD=heritage
    depends_on:
      - db
    ports:
      - 8080:80
